version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/home_maintenance
      - NODE_ENV=production
    depends_on:
      - db
    volumes:
      - ./data/uploads:/app/data/uploads

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=home_maintenance
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local